# Changes here will be overwritten by Copier
_commit: v1.5.6
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_tz: UTC
cidr_whitelist: null
domain_prod: demo-docker.simetri-sinergi.id
domain_prod_alternatives: null
domain_test: null
gitlab_url: null
odoo_dbfilter: .*
odoo_initial_lang: en_US
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 10.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 10
project_author: PT. Simetri Sinergi Indonesia
project_license: AGPL-3.0-or-later
project_name: test-copier-8
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null
