version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "$INITIAL_LANG"
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      traefik.longpolling.frontend.rule: "Host:${DOMAIN_PROD};PathPrefix:/longpolling/"
      traefik.www.frontend.rule: "Host:${DOMAIN_PROD}"
      traefik.forbid-crawlers.frontend.rule: "Host:${DOMAIN_PROD};PathPrefix:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}"
      # Main service
      ? traefik.http.middlewares.test-copier-8-10-0-prod-buffering.buffering.retryExpression
      : IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.test-copier-8-10-0-prod-compress.compress: "true"
      traefik.http.routers.test-copier-8-10-0-prod-main.entrypoints: "web-main"
      traefik.http.routers.test-copier-8-10-0-prod-main.middlewares:
        test-copier-8-10-0-prod-buffering, test-copier-8-10-0-prod-compress
      traefik.http.routers.test-copier-8-10-0-prod-main.rule: "host(`${DOMAIN_PROD}`)"
      traefik.http.routers.test-copier-8-10-0-prod-main.service: "test-copier-8-10-0-prod-main"
      traefik.http.routers.test-copier-8-10-0-prod-main.tls: "true"
      traefik.http.routers.test-copier-8-10-0-prod-main.tls.certresolver: "letsencrypt"
      traefik.http.services.test-copier-8-10-0-prod-main.loadbalancer.server.port: 8069
      # Longpolling service
      traefik.http.routers.test-copier-8-10-0-prod-longpolling.entrypoints: "web-main"
      traefik.http.routers.test-copier-8-10-0-prod-longpolling.rule:
        "host(`${DOMAIN_PROD}`) && pathprefix(`/longpolling/`)"
      traefik.http.routers.test-copier-8-10-0-prod-longpolling.service: "test-copier-8-10-0-prod-longpolling"
      traefik.http.services.test-copier-8-10-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.test-copier-8-10-0-prod-longpolling.tls: "true"
      traefik.http.routers.test-copier-8-10-0-prod-longpolling.tls.certresolver: "letsencrypt"
      # Forbid crawlers
      ? traefik.http.middlewares.test-copier-8-10-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.routers.test-copier-8-10-0-prod-forbidden-crawlers.entrypoints: "web-main"
      traefik.http.routers.test-copier-8-10-0-prod-forbidden-crawlers.middlewares:
        test-copier-8-10-0-prod-buffering, test-copier-8-10-0-prod-compress,
        test-copier-8-10-0-prod-forbid-crawlers
      traefik.http.routers.test-copier-8-10-0-prod-forbidden-crawlers.rule:
        Host(`${DOMAIN_PROD}`) && Path(`/web`, `/web/{anything:.*}`, `/website/info`,
        `/website/info/{anything:.*}`)
      traefik.http.routers.test-copier-8-10-0-prod-forbidden-crawlers.service: "test-copier-8-10-0-prod-main"
      traefik.http.routers.test-copier-8-10-0-prod-forbidden-crawlers.tls: "true"
      traefik.http.routers.test-copier-8-10-0-prod-forbidden-crawlers.tls.certresolver: "letsencrypt"

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
